#!/usr/bin/env python3
from pathlib import Path


def replace_once(path: Path, old: str, new: str) -> None:
    text = path.read_text(encoding="utf-8")
    if new in text:
        return
    if old not in text:
        raise SystemExit(f"target not found in {path}: {old[:80]!r}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


corpus = Path("library_slab_corpus.py")

old_prepare = '''def _prepare_crop(source: Image.Image, top_fraction: float, scale: float, threshold: bool) -> Image.Image:\n    width, height = source.size\n    crop = source.crop((0, 0, width, max(1, int(height * top_fraction))))\n    crop = ImageOps.autocontrast(ImageOps.grayscale(crop))\n    if threshold:\n        crop = crop.point(lambda p: 255 if p > 172 else 0)\n    target_w = max(900, int(width * scale))\n    ratio = target_w / max(1, crop.width)\n    target_h = max(300, int(crop.height * ratio))\n    return crop.resize((target_w, target_h))\n\n\ndef _run_tesseract(image: Image.Image, psm: int) -> tuple[str, str | None]:\n'''
new_prepare = '''def _prepare_crop(source: Image.Image, top_fraction: float, scale: float, threshold: bool) -> Image.Image:\n    width, height = source.size\n    crop = source.crop((0, 0, width, max(1, int(height * top_fraction))))\n    crop = ImageOps.autocontrast(ImageOps.grayscale(crop))\n    if threshold:\n        crop = crop.point(lambda p: 255 if p > 172 else 0)\n    target_w = max(900, int(width * scale))\n    ratio = target_w / max(1, crop.width)\n    target_h = max(300, int(crop.height * ratio))\n    return crop.resize((target_w, target_h))\n\n\ndef _prepare_region_crop(\n    source: Image.Image, left: float, top: float, right: float, bottom: float,\n    target_width: int, threshold: bool = False,\n) -> Image.Image:\n    \"\"\"Prepare a bounded label sub-region for grader-specific OCR recovery.\"\"\"\n    width, height = source.size\n    x0 = max(0, min(width - 1, int(width * left)))\n    y0 = max(0, min(height - 1, int(height * top)))\n    x1 = max(x0 + 1, min(width, int(width * right)))\n    y1 = max(y0 + 1, min(height, int(height * bottom)))\n    crop = source.crop((x0, y0, x1, y1))\n    crop = ImageOps.autocontrast(ImageOps.grayscale(crop))\n    if threshold:\n        crop = crop.point(lambda p: 255 if p > 172 else 0)\n    target_w = max(900, int(target_width))\n    ratio = target_w / max(1, crop.width)\n    return crop.resize((target_w, max(240, int(crop.height * ratio))))\n\n\ndef _run_tesseract(\n    image: Image.Image, psm: int, whitelist: str | None = None,\n) -> tuple[str, str | None]:\n'''
replace_once(corpus, old_prepare, new_prepare)

old_run = '''            run = subprocess.run(\n                ["tesseract", tmp.name, "stdout", "--psm", str(psm), "-l", "eng"],\n                capture_output=True,\n'''
new_run = '''            command = ["tesseract", tmp.name, "stdout", "--psm", str(psm), "-l", "eng"]\n            if whitelist:\n                command += ["-c", f"tessedit_char_whitelist={whitelist}"]\n            run = subprocess.run(\n                command,\n                capture_output=True,\n'''
replace_once(corpus, old_run, new_run)

old_fields = '''def _fields_from_text(text: str) -> tuple[str | None, str | None, float | None]:\n    company = detect_company(text)\n    cert = normalize_cert(company, text)\n    grade = normalize_grade(text, company)\n    return company, cert, grade\n'''
new_fields = '''def _looks_like_bgs_label(text: str) -> bool:\n    upper = _normalized_ocr(text)\n    markers = sum(token in upper for token in ("CENTERING", "CORNERS", "EDGES", "SURFACE"))\n    return ("BECKETT" in upper or " BGS " in f" {upper} " or "PRISTINE" in upper) and markers >= 2\n\n\ndef _fields_from_text(text: str) -> tuple[str | None, str | None, float | None]:\n    company = detect_company(text)\n    if company is None and _looks_like_bgs_label(text):\n        company = "BGS"\n    cert = normalize_cert(company, text)\n    grade = normalize_grade(text, company)\n    return company, cert, grade\n'''
replace_once(corpus, old_fields, new_fields)

old_loop = '''            texts: list[str] = []\n            errors: list[str] = []\n            used: list[str] = []\n            for name, fraction, scale, threshold, psm in passes:\n                crop = _prepare_crop(source, fraction, scale, threshold)\n                text, error = _run_tesseract(crop, psm)\n                used.append(name)\n                if text:\n                    texts.append(text)\n                if error:\n                    errors.append(error)\n\n                combined = " | ".join(texts)\n                company, cert, grade = _fields_from_text(combined)\n                if profile == "adaptive" and company and cert and grade is not None:\n                    break\n'''
new_loop = '''            texts: list[str] = []\n            errors: list[str] = []\n            used: list[str] = []\n            bgs_cert_targeted = False\n            for name, fraction, scale, threshold, psm in passes:\n                crop = _prepare_crop(source, fraction, scale, threshold)\n                text, error = _run_tesseract(crop, psm)\n                used.append(name)\n                if text:\n                    texts.append(text)\n                if error:\n                    errors.append(error)\n\n                combined = " | ".join(texts)\n                company, cert, grade = _fields_from_text(combined)\n\n                # Beckett/BGS labels place a small serial at the far-right of the\n                # top label. On Android/Termux the normal PSM-6 pass can read the\n                # large grade/subgrades yet skip this small leading-zero number.\n                # Run a narrow digits-only recovery pass only when BGS identity is\n                # already visually supported and the certificate is unresolved.\n                if not bgs_cert_targeted and cert is None and (company == "BGS" or _looks_like_bgs_label(combined)):\n                    bgs_cert_targeted = True\n                    cert_crop = _prepare_region_crop(source, 0.48, 0.00, 1.00, 0.20, 1700, False)\n                    cert_text, cert_error = _run_tesseract(\n                        cert_crop, 6, whitelist="0123456789"\n                    )\n                    used.append("bgs_top_right_digits_psm6")\n                    if cert_error:\n                        errors.append(cert_error)\n                    recovered = normalize_cert("BGS", cert_text or "")\n                    if recovered is None:\n                        cert_text2, cert_error2 = _run_tesseract(\n                            cert_crop, 11, whitelist="0123456789"\n                        )\n                        used.append("bgs_top_right_digits_psm11")\n                        if cert_error2:\n                            errors.append(cert_error2)\n                        recovered = normalize_cert("BGS", cert_text2 or "")\n                    if recovered:\n                        # Synthetic CERT context is created only from a valid BGS\n                        # length candidate, preserving leading zeroes and making\n                        # downstream evidence extraction deterministic.\n                        texts.append(f"BECKETT CERT {recovered}")\n                    combined = " | ".join(texts)\n                    company, cert, grade = _fields_from_text(combined)\n\n                if profile == "adaptive" and company and cert and grade is not None:\n                    break\n'''
replace_once(corpus, old_loop, new_loop)

# Make the BGS overall grade extractor recognize the common "10 PRISTINE" label order.
evidence = Path("graded_photo_evidence.py")
old_grade = '''GRADE_PATTERNS = (\n    re.compile(r"\\b(?:PSA|BGS|CGC|TAG|BRG|BECKETT)\\s*(?:GRADE\\s*)?(?:(?:GEM\\s*(?:MT|MINT)|PRISTINE|BLACK\\s+LABEL|MINT|NM-MT|NEAR\\s+MINT)\\s*)?(10|9\\.5|9|8\\.5|8|7\\.5|7|6\\.5|6|5\\.5|5|4\\.5|4|3\\.5|3|2\\.5|2|1\\.5|1)\\b", re.I),\n    re.compile(r"\\b(?:FINAL\\s+GRADE|CARD\\s+GRADE|ITEM\\s+GRADE|GRADE)\\s*(?:GEM\\s*MT|GEM\\s*MINT|PRISTINE|MINT|NM-MT)?\\s*(10|9\\.5|9|8\\.5|8|7\\.5|7|6\\.5|6|5\\.5|5|4\\.5|4|3\\.5|3|2\\.5|2|1\\.5|1)\\b", re.I),\n    re.compile(r"(?:등급|그레이드|감정)\\s*(10|9\\.5|9|8\\.5|8|7\\.5|7|6\\.5|6|5\\.5|5|4\\.5|4|3\\.5|3|2\\.5|2|1\\.5|1)", re.I),\n)\n'''
new_grade = '''GRADE_PATTERNS = (\n    re.compile(r"\\b(?:PSA|BGS|CGC|TAG|BRG|BECKETT)\\s*(?:GRADE\\s*)?(?:(?:GEM\\s*(?:MT|MINT)|PRISTINE|BLACK\\s+LABEL|MINT|NM-MT|NEAR\\s+MINT)\\s*)?(10|9\\.5|9|8\\.5|8|7\\.5|7|6\\.5|6|5\\.5|5|4\\.5|4|3\\.5|3|2\\.5|2|1\\.5|1)\\b", re.I),\n    re.compile(r"\\b(?:FINAL\\s+GRADE|CARD\\s+GRADE|ITEM\\s+GRADE|GRADE)\\s*(?:GEM\\s*MT|GEM\\s*MINT|PRISTINE|MINT|NM-MT)?\\s*(10|9\\.5|9|8\\.5|8|7\\.5|7|6\\.5|6|5\\.5|5|4\\.5|4|3\\.5|3|2\\.5|2|1\\.5|1)\\b", re.I),\n    re.compile(r"\\b(10|9\\.5|9|8\\.5|8|7\\.5|7|6\\.5|6|5\\.5|5|4\\.5|4|3\\.5|3|2\\.5|2|1\\.5|1)\\s*(?:PRISTINE|BLACK\\s+LABEL|GEM\\s*(?:MT|MINT)|MINT|NM-MT|NEAR\\s+MINT)\\b", re.I),\n    re.compile(r"(?:등급|그레이드|감정)\\s*(10|9\\.5|9|8\\.5|8|7\\.5|7|6\\.5|6|5\\.5|5|4\\.5|4|3\\.5|3|2\\.5|2|1\\.5|1)", re.I),\n)\n'''
replace_once(evidence, old_grade, new_grade)

print("BGS targeted certificate OCR v169 applied")
