from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')
old=''' const card=(x,query,region)=>{const score=sourceProbability(x,region),[lab,cls]=probLabel(score),distance=(purchaseLocation&&Number.isFinite(Number(x.lat))&&Number.isFinite(Number(x.lon)))?haversineKm(purchaseLocation,{lat:Number(x.lat),lon:Number(x.lon)}):null,address=x.address?`<br><span class="store-address">${escapeDisplayText(x.address)}</span>`:"",phone=x.phone?` · ☎ ${escapeDisplayText(x.phone)}`:"",stock=(x.channel||"online")==="offline"?`<br><span class="store-stock">${escapeDisplayText(x.inventory_status||"TCG 취급·재고 미확인 · 방문 전 전화 확인")}</span>${phone}`:"",retailer=RETAILER_LABELS[x.retailer_category]&&x.retailer_category!=="general"?`<span class="source-badge">${escapeDisplayText(RETAILER_LABELS[x.retailer_category])}</span>`:"";return `<a class="purchase-source" href="${purchaseUrl(x,query)}" target="_blank" rel="noopener noreferrer"><b>${escapeDisplayText(x.name)}<span class="source-badge ${escapeDisplayText(x.type)}">${escapeDisplayText(types[x.type]||"구매처")}</span>${retailer}<span class="purchase-prob ${cls}">참고 ${lab} ${score}</span></b><small>${escapeDisplayText(x.note||"")}${address}${distance!==null?`<br><span class="purchase-source-distance">${escapeDisplayText(purchaseLocation?.label||"현재 위치")}에서 약 ${distance.toFixed(1)} km</span>`:""}${stock}<br>${(x.channel||"online")==="offline"?"지도·전화로 영업 및 카드 재고 최종 확인":"현재 구매 가능 여부는 판매처에서 확인"}</small></a>`};'''
new=''' const purchaseCapability=x=>{const channel=x.channel||"online",hasStock=Boolean(x.stock_url||x.inventory_url||x.stock_lookup_url||x.realtime_inventory===true);if(hasStock)return {key:"stock",label:"🟢 재고조회 지원",note:"판매처가 제공하는 재고조회 화면으로 이동합니다. 표시 시점과 실제 매장 재고는 다를 수 있습니다."};if(channel==="offline")return {key:"store",label:"📍 매장찾기·전화확인",note:"온라인 재고조회 기능은 확인되지 않았습니다. 공식 매장찾기·지도·전화로 취급 및 재고를 확인하세요."};if(x.type==="marketplace"||x.type==="used")return {key:"search",label:"🛒 상품검색",note:"판매 상품 검색으로 이동합니다. 실시간 재고 보장은 아니며 판매자별 상태를 확인하세요."};return {key:"info",label:"ℹ️ 공식안내",note:"제품·출시·매장 안내용 공식 페이지입니다. 재고조회 기능은 확인되지 않았습니다."}};
 const card=(x,query,region)=>{const score=sourceProbability(x,region),distance=(purchaseLocation&&Number.isFinite(Number(x.lat))&&Number.isFinite(Number(x.lon)))?haversineKm(purchaseLocation,{lat:Number(x.lat),lon:Number(x.lon)}):null,address=x.address?`<br><span class="store-address">${escapeDisplayText(x.address)}</span>`:"",phone=x.phone?` · ☎ ${escapeDisplayText(x.phone)}`:"",cap=purchaseCapability(x),stock=(x.channel||"online")==="offline"?`<br><span class="store-stock">${escapeDisplayText(x.inventory_status||"TCG 취급·재고 미확인")}</span>${phone}`:"",retailer=RETAILER_LABELS[x.retailer_category]&&x.retailer_category!=="general"?`<span class="source-badge">${escapeDisplayText(RETAILER_LABELS[x.retailer_category])}</span>`:"";return `<a class="purchase-source" href="${purchaseUrl(x,query)}" target="_blank" rel="noopener noreferrer"><b>${escapeDisplayText(x.name)}<span class="source-badge ${escapeDisplayText(x.type)}">${escapeDisplayText(types[x.type]||"구매처")}</span>${retailer}<span class="source-badge capability ${cap.key}">${cap.label}</span><span class="source-confidence">출처 ${score}</span></b><small>${escapeDisplayText(x.note||"")}${address}${distance!==null?`<br><span class="purchase-source-distance">${escapeDisplayText(purchaseLocation?.label||"현재 위치")}에서 약 ${distance.toFixed(1)} km</span>`:""}${stock}<br><span class="capability-note">${cap.note}</span></small></a>`};'''
if old not in s:
    raise SystemExit('target card renderer not found')
s=s.replace(old,new,1)
s=s.replace('📍 오프라인 매장·지도','📍 오프라인 매장·확인',1)
s=s.replace('지도·전화로 영업 및 카드 재고 최종 확인','매장찾기·전화로 취급 및 재고 확인',1)
p.write_text(s,encoding='utf-8')
print('purchase capability labels patched')
