#!/usr/bin/env python3
from pathlib import Path

path = Path("manual_graded_photo_registration.py")
text = path.read_text(encoding="utf-8")
old = '''def _public_row(row: dict[str, Any]) -> dict[str, Any]:\n    keys = (\n        "registration_id", "created_at", "updated_at", "company", "game", "claimed_grade",\n        "certification_id", "card_name", "card_number", "image_sha256", "image_width",\n        "image_height", "status", "verification_state", "official_result",\n        "official_reference_url", "learning_eligibility", "training_eligible",\n        "quarantine_reasons", "ocr_company", "ocr_grade", "ocr_certification_id",\n        "ocr_error", "ocr_cache_hit", "retry_after_seconds", "duplicate_of",\n        "entry_mode", "manual_identity_complete", "missing_identity_fields",\n        "back_image_sha256", "back_image_width", "back_image_height", "front_back_pair_complete",\n        "front_oblique_image_sha256", "back_oblique_image_sha256", "oblique_crosscheck_complete",\n        "quadrant_zone_count", "quadrant_inspection_state", "measurement_learning_eligible",\n        "client_preview_training_eligible", "photo_revalidation",\n    )\n    return {key: row.get(key) for key in keys if key in row}\n'''
new = '''def _public_row(row: dict[str, Any]) -> dict[str, Any]:\n    keys = (\n        "registration_id", "created_at", "updated_at", "company", "game", "claimed_grade",\n        "certification_id", "card_name", "card_number", "image_sha256", "image_width",\n        "image_height", "status", "verification_state", "official_result",\n        "official_reference_url", "learning_eligibility", "training_eligible",\n        "quarantine_reasons", "ocr_company", "ocr_grade", "ocr_certification_id",\n        "ocr_error", "ocr_cache_hit", "retry_after_seconds", "duplicate_of",\n        "entry_mode", "manual_identity_complete", "missing_identity_fields",\n        "back_image_sha256", "back_image_width", "back_image_height", "front_back_pair_complete",\n        "front_oblique_image_sha256", "back_oblique_image_sha256", "oblique_crosscheck_complete",\n        "quadrant_zone_count", "quadrant_inspection_state", "measurement_learning_eligible",\n        "client_preview_training_eligible", "photo_revalidation",\n    )\n    public = {key: row.get(key) for key in keys if key in row}\n    # v190: Older tablet-local BRG registrations may still contain the retired\n    # brgcard.com URL. Never expose that stale stored URL when the registration\n    # already has a certificate identity; regenerate the current Break Korea\n    # direct certification URL instead. This repairs existing rows at read time\n    # without rewriting or deleting the user's local registration history.\n    company = str(row.get("company") or row.get("ocr_company") or "").upper()\n    cert = _normalized_cert(row.get("certification_id") or row.get("ocr_certification_id"))\n    if company == "BRG" and cert:\n        public["official_reference_url"] = lookup_url("BRG", cert)\n    return public\n'''
if new in text:
    print("BRG registered-link normalization v190 already applied")
elif old not in text:
    raise SystemExit("target _public_row block not found")
else:
    path.write_text(text.replace(old, new, 1), encoding="utf-8")
    print("BRG registered-link normalization v190 applied")
