/* v328 fail-closed card metadata classification and price binding.
 * Separates game/edition/card number/set/rarity/variant/product/grade context.
 * Unknown or conflicting identity is never silently promoted to an exact price.
 */
(function(root){
'use strict';
const GAMES=new Set(['pokemon','onepiece','naruto']);
const REGIONS=new Set(['KR','JP','US']);
const COMPANIES=new Set(['PSA','BGS','CGC','TAG','BRG']);
const norm=v=>String(v??'').normalize?.('NFKC').toUpperCase().replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim();
const compact=v=>norm(v).replace(/\s+/g,'');
const plain=v=>norm(v).replace(/[^0-9A-Z가-힣ぁ-んァ-ヶ一-龯/+. -]/g,'').trim();
const nameKey=v=>norm(v).replace(/[^0-9A-Z가-힣ぁ-んァ-ヶ一-龯]/g,'');
function game(v){const s=norm(v);if(/POK[ÉE]MON|포켓몬/.test(s))return'pokemon';if(/ONE\s*PIECE|원피스/.test(s))return'onepiece';if(/NARUTO|나루토/.test(s))return'naruto';const raw=String(v||'').toLowerCase();return GAMES.has(raw)?raw:'unknown'}
function region(v){const s=compact(v);if(/^(KR|KOR|KOREA|KOREAN|한국|한국판|한글판|한판|국판)$/.test(s))return'KR';if(/^(JP|JPN|JAPAN|JAPANESE|日本|日本版|日版|일본판|일판)$/.test(s))return'JP';if(/^(US|USA|EN|ENG|ENGLISH|미국|미국판|영문판|영판)$/.test(s))return'US';return'UNKNOWN'}
function regionFromKey(v){const first=String(v||'').split('|',1)[0].toUpperCase();return REGIONS.has(first)?first:'UNKNOWN'}
function normalizeCardNumber(v){let s=compact(v).replace(/[–—]/g,'-'),m;if((m=s.match(/^(OP|ST|EB|PRB)-?(\d{1,2})-?(\d{1,3})$/)))return `${m[1]}${m[2].padStart(2,'0')}-${m[3].padStart(3,'0')}`;if((m=s.match(/^(CP|NR|NAR|PR)-?(\d{1,4})$/)))return `${m[1]}-${m[2].padStart(3,'0')}`;if((m=s.match(/^((?:SV|SM|XY|BW)\d+[A-Z]?|S\d+[A-Z]?|M\d{1,2}[A-Z]?|MEG|PFL|ASC|POR|CRI|PBL|PAL|OBF|MEW|PAR|PAF|TEF|TWM|SFA|SCR|SSP|PRE|JTG|DRI|BLK|WHT)-?(\d{1,3}(?:\/\d{2,3})?)$/)))return m[1]+m[2];if((m=s.match(/^(\d{1,3})\/(\d{2,3})$/)))return `${Number(m[1])}/${Number(m[2])}`;return s.replace(/[^0-9A-Z/.-]/g,'').slice(0,40)}
function setCode(g,text){const s=norm(text),number=normalizeCardNumber(text);let m;if(g==='onepiece'){m=number.match(/^(OP|ST|EB|PRB)(\d{2})-/)||s.match(/(?:^|[^A-Z0-9])(OP|ST|EB|PRB)[KJ-]?\s*-?\s*(\d{1,2})(?=[^0-9]|$)/);if(m)return m[1]+'-'+m[2].padStart(2,'0')}if(g==='naruto'){m=number.match(/^(CP|NR|NAR|PR)-/);if(m)return m[1]}if(g==='pokemon'){m=number.match(/^((?:SV|SM|XY|BW)\d+[A-Z]?|S\d+[A-Z]?|M\d{1,2}[A-Z]?|MEG|PFL|ASC|POR|CRI|PBL|PAL|OBF|MEW|PAR|PAF|TEF|TWM|SFA|SCR|SSP|PRE|JTG|DRI|BLK|WHT)/)||s.match(/(?:^|[^A-Z0-9])((?:SV|SM|XY|BW)\d+[A-Z]?|S\d+[A-Z]?|M\d{1,2}[A-Z]?|MEG|PFL|ASC|POR|CRI|PBL|PAL|OBF|MEW|PAR|PAF|TEF|TWM|SFA|SCR|SSP|PRE|JTG|DRI|BLK|WHT)(?=\s*-?\s*\d|[^A-Z0-9]|$)/);if(m)return m[1]}return''}
function rarity(g,text){const s=' '+norm(text)+' ';const ordered=g==='pokemon'?['SAR','UR','HR','SR','AR','CHR','CSR','ACE SPEC','RRR','RR','R','U','C','PROMO']:g==='onepiece'?['SP','SEC','L','SR','R','UC','C','P']:g==='naruto'?['MYTHIC','SECRET','SUPER RARE','RARE','UNCOMMON','COMMON','PROMO']:[];for(const r of ordered){const rx=new RegExp('(?:^|[^A-Z])'+r.replace(' ','\\s+')+'(?:$|[^A-Z])');if(rx.test(s))return r}return'UNKNOWN'}
function variant(g,text){const s=norm(text);if(/MASTER\s*BALL|마스터볼|マスターボール/.test(s))return'master_ball';if(/POK[ÉE]\s*BALL|포켓볼|モンスターボール/.test(s))return'poke_ball';if(/REVERSE\s*HOLO|리버스\s*홀로/.test(s))return'reverse_holo';if(/STAMP(?:ED)?|스탬프|スタンプ/.test(s))return'stamped';if(/MANGA|만화\s*패러렐|コミパラ/.test(s))return'manga_parallel';if(/ALT(?:ERNATE)?\s*ART|패러렐|PARALLEL|パラレル/.test(s))return'parallel';if(/PROMO|프로모|プロモ/.test(s))return'promo';if(/1ST\s*EDITION|초판/.test(s))return'first_edition';if(/(?:^|[^A-Z])(?:BASE|STANDARD|REGULAR)(?:[^A-Z]|$)|일반판|통상판|通常版/.test(s))return'base';return'UNSPECIFIED'}
function productType(text){const s=norm(text);if(/\bCASE\b|카톤|CARTON/.test(s))return'CASE';if(/\bBOX\b|박스|BOOSTER\s*BOX/.test(s))return'BOX';if(/BUNDLE|묶음|세트\s*상품/.test(s))return'BUNDLE';if(/\bPACK\b|팩\b|BOOSTER\s*PACK/.test(s))return'PACK';return'CARD'}
function gradeContext(input={},text=''){const explicitCompany=norm(input.grading_company||input.company||''),s=norm(text),company=COMPANIES.has(explicitCompany)?explicitCompany:(s.match(/\b(PSA|BGS|CGC|TAG|BRG)\b/)||[])[1]||'';let grade=Number(input.grade);if(!Number.isFinite(grade)){const re=company?new RegExp('\\b'+company+'\\s*(10(?:\\.0)?|[1-9](?:\\.5)?)\\b'):/\b(?:GRADE|등급)\s*(10(?:\.0)?|[1-9](?:\.5)?)\b/;const m=s.match(re);grade=m?Number(m[1]):NaN}const explicitRaw=/(?:^|[^A-Z])(?:RAW|UNGRADED)(?:[^A-Z]|$)|미감정/.test(s)||String(input.condition||'').toLowerCase()==='raw';if(company&&Number.isFinite(grade))return{grade_state:'graded',grading_company:company,grade};if(explicitRaw)return{grade_state:'raw',grading_company:'',grade:null};return{grade_state:'unknown',grading_company:'',grade:null}}
function generation(g,code){if(g!=='pokemon')return{generation:null,generation_label:'해당 없음',era:'N/A',generation_status:'not_applicable'};if(/^SV/.test(code)||['PAL','OBF','MEW','PAR','PAF','TEF','TWM','SFA','SCR','SSP','PRE','JTG','DRI','BLK','WHT'].includes(code))return{generation:9,generation_label:'9세대',era:'SV',generation_status:'set_evidence'};if(/^S\d/.test(code))return{generation:8,generation_label:'8세대',era:'S',generation_status:'set_evidence'};if(/^SM/.test(code))return{generation:7,generation_label:'7세대',era:'SM',generation_status:'set_evidence'};if(/^XY/.test(code))return{generation:6,generation_label:'6세대',era:'XY',generation_status:'set_evidence'};if(/^BW/.test(code))return{generation:5,generation_label:'5세대',era:'BW',generation_status:'set_evidence'};if(/^DP|^DPT/.test(code))return{generation:4,generation_label:'4세대',era:'DP',generation_status:'set_evidence'};if(/^M\d/.test(code)||['MEG','PFL','ASC','POR','CRI','PBL'].includes(code))return{generation:null,generation_label:'세대 단정 안 함',era:'MEGA',generation_status:'series_only'};return{generation:null,generation_label:'세대 확인 필요',era:'UNKNOWN',generation_status:'unknown'}}
function classify(input={}){const g=game(input.game),keyRegion=regionFromKey(input.market_key),r=region(input.region)!=='UNKNOWN'?region(input.region):keyRegion,text=[input.card_name,input.card_number,input.product_name,input.title,input.ocr_text,input.market_key,input.rarity,input.variant,input.condition,input.grading_company,input.grade].filter(v=>v!==undefined&&v!==null&&v!=='').join(' '),number=normalizeCardNumber(input.card_number||''),code=setCode(g,[number,text].join(' ')),ra=rarity(g,[input.rarity||'',text].join(' ')),vr=variant(g,[input.variant||'',text].join(' ')),pt=productType([input.product_type||'',input.market_key||'',input.product_name||'',input.title||''].join(' ')),gen=generation(g,code),grade=gradeContext(input,text),cardName=plain(input.card_name||input.title||'').slice(0,160),evidence=[g!=='unknown'&&'game',r!=='UNKNOWN'&&'region',number&&'card_number',cardName&&'card_name',code&&'set_code',ra!=='UNKNOWN'&&'rarity',vr!=='UNSPECIFIED'&&'variant',grade.grade_state!=='unknown'&&'grade_state'].filter(Boolean);return{version:'v328',game:g,region:r,card_name:cardName,card_name_key:nameKey(cardName),card_number:number,set_code:code,rarity:ra,variant:vr,product_type:pt,...grade,...gen,identity_key:[g,r,number,nameKey(cardName)].join('|'),variant_key:[g,r,number,code,ra,vr].join('|'),evidence_count:evidence.length,evidence,status:g==='unknown'?'unknown':'classified'}}
function namesCompatible(a,b){if(!a||!b)return true;return a===b||a.length>=4&&b.includes(a)||b.length>=4&&a.includes(b)}
function bindPrice(card,market={}){const c=card?.version==='v328'?card:classify(card||{}),m=market?.version==='v328'?market:classify(market||{}),conflicts=[];if(c.game==='unknown'||m.game==='unknown')conflicts.push('game_missing');else if(c.game!==m.game)conflicts.push('game');if(c.region==='UNKNOWN'||m.region==='UNKNOWN')conflicts.push('region_missing');else if(c.region!==m.region)conflicts.push('region');if(c.product_type!==m.product_type)conflicts.push('product_type');if(c.product_type==='CARD'){if(!c.card_number||!m.card_number)conflicts.push('card_number_missing');else if(c.card_number!==m.card_number)conflicts.push('card_number');if(c.set_code&&m.set_code&&c.set_code!==m.set_code)conflicts.push('set_code');else if((c.set_code||m.set_code)&&!(c.set_code&&m.set_code))conflicts.push('set_code_missing');else if(!c.set_code&&!m.set_code&&/^\d+\/\d+$/.test(c.card_number||''))conflicts.push('set_code_missing');if(!namesCompatible(c.card_name_key,m.card_name_key))conflicts.push('card_name');if(c.rarity!=='UNKNOWN'&&m.rarity!=='UNKNOWN'&&c.rarity!==m.rarity)conflicts.push('rarity');if(c.variant!==m.variant&&(c.variant!=='UNSPECIFIED'||m.variant!=='UNSPECIFIED'))conflicts.push('variant')}if(c.grade_state!==m.grade_state){if(c.grade_state!=='unknown'||m.grade_state!=='unknown')conflicts.push('grade_state')}else if(c.grade_state==='graded'){if(c.grading_company!==m.grading_company)conflicts.push('grading_company');if(Number(c.grade)!==Number(m.grade))conflicts.push('grade')}const unique=[...new Set(conflicts)],identitySafe=unique.filter(x=>!['variant','grade_state','grading_company','grade'].includes(x)).length===0,variantVerified=c.product_type!=='CARD'||(c.variant!=='UNSPECIFIED'&&m.variant!=='UNSPECIFIED'&&c.variant===m.variant),gradeVerified=c.grade_state===m.grade_state&&c.grade_state!=='unknown'&&(c.grade_state==='raw'||(c.grading_company===m.grading_company&&Number(c.grade)===Number(m.grade))),priceSafe=identitySafe&&variantVerified&&gradeVerified&&unique.length===0;let priceStatus='blocked';if(identitySafe&&!priceSafe)priceStatus='identity_match_context_unverified';if(priceSafe)priceStatus='exact_variant_grade_match';return{safe:priceSafe,identity_safe:identitySafe,price_safe:priceSafe,price_status:priceStatus,conflicts:unique,card_variant_key:c.variant_key,market_variant_key:m.variant_key,card_context:{game:c.game,region:c.region,set_code:c.set_code,rarity:c.rarity,variant:c.variant,product_type:c.product_type,grade_state:c.grade_state,grading_company:c.grading_company,grade:c.grade},market_context:{game:m.game,region:m.region,set_code:m.set_code,rarity:m.rarity,variant:m.variant,product_type:m.product_type,grade_state:m.grade_state,grading_company:m.grading_company,grade:m.grade},note:priceSafe?'동일 게임/판본/카드/세트/variant/등급상태 확인':'자동 시세 확정 금지 · 누락/불일치 문맥은 참고만 표시'}}
root.TCGCardMetadata=Object.freeze({version:'v328',classify,bindPrice,normalizeCardNumber});
})(typeof window!=='undefined'?window:globalThis);
