/* v109 confirmation-only card-name/card-number recognition learning. */
(()=>{
'use strict';
const MEMORY_KEY='tcg_card_identity_learning_v1',MAX_LOCAL=500;
const byId=id=>document.getElementById(id);
const safeText=value=>String(value??'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,180);
const gameName=value=>['pokemon','onepiece','naruto'].includes(value)?value:'pokemon';
function localRows(){try{const value=JSON.parse(localStorage.getItem(MEMORY_KEY)||'[]');return Array.isArray(value)?value.filter(row=>row&&row.confirmed===true).slice(-MAX_LOCAL):[]}catch(_){return []}}
function hamming(a,b){if(!/^[0-9a-f]{16}$/.test(a)||!/^[0-9a-f]{16}$/.test(b))return 65;let value=BigInt('0x'+a)^BigInt('0x'+b),count=0;while(value){count+=Number(value&1n);value>>=1n}return count}
async function imageData(file){const image=await window.loadCardImage(file),scale=Math.min(1,1400/image.naturalWidth,1900/image.naturalHeight),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('canvas');ctx.drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.84)}
async function imageHash(file){const image=await window.loadCardImage(file),canvas=document.createElement('canvas');canvas.width=9;canvas.height=8;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)throw new Error('canvas');ctx.drawImage(image,0,0,9,8);const data=ctx.getImageData(0,0,9,8).data,gray=[];for(let i=0;i<data.length;i+=4)gray.push((data[i]*299+data[i+1]*587+data[i+2]*114)/1000);let bits=0n;for(let y=0;y<8;y++)for(let x=0;x<8;x++)bits=(bits<<1n)|(gray[y*9+x]>gray[y*9+x+1]?1n:0n);return bits.toString(16).padStart(16,'0')}
async function browserText(file){if(typeof window.TextDetector!=='function'||typeof createImageBitmap!=='function')return '';try{const bitmap=await createImageBitmap(file),rows=await new TextDetector().detect(bitmap);bitmap.close?.();return rows.map(row=>row.rawValue||'').join(' ').slice(0,5000)}catch(_){return ''}}
function learnedCandidates(hash,game){const rows=localRows().filter(row=>row.game===game),counts=new Map();for(const row of rows){const key=[row.card_name,row.card_number,row.market_key].join('|');counts.set(key,(counts.get(key)||0)+1)}const hits=[];for(const row of rows){const distance=hamming(hash,row.image_hash),key=[row.card_name,row.card_number,row.market_key].join('|');if(distance===0||(distance<=8&&(counts.get(key)||0)>=3))hits.push({...row,confidence:distance===0?.999:Math.max(.86,.98-distance*.012),matched_by:distance===0?'confirmed_exact_image':'confirmed_visual_learning'})}return hits.sort((a,b)=>b.confidence-a.confidence).slice(0,5)}
function mergeCandidates(rows){const found=new Map();for(const row of rows.filter(Boolean)){const key=[row.card_name,row.card_number,row.market_key].join('|'),old=found.get(key);if(!old||Number(row.confidence)>Number(old.confidence))found.set(key,row)}return [...found.values()].sort((a,b)=>Number(b.confidence)-Number(a.confidence)).slice(0,5)}
function displayCandidates(rows){const select=byId('identityCandidates');select.innerHTML='';if(!rows.length){select.append(new Option('일치 후보 없음 · 직접 확인 입력',''));return}rows.forEach((row,index)=>{const option=new Option(`${Math.round(Number(row.confidence)*100)}% · ${row.card_name}${row.card_number?' · '+row.card_number:''}`,String(index));select.append(option)});select._rows=rows;select.value='0';applyCandidate(rows[0])}
function applyCandidate(row){if(!row)return;byId('identityCardName').value=safeText(row.card_name);byId('identityCardNumber').value=safeText(row.card_number);byId('identityMarketKey').value=safeText(row.market_key);byId('identityRegion').value=['KR','JP','US'].includes(row.region)?row.region:'UNKNOWN'}
async function recognize(game){const file=window.tcgCardInputFile?.('front');if(!file){byId('identityStatus').textContent='앞면 사진이 없어 카드명을 인식할 수 없습니다.';return null}const status=byId('identityStatus');status.textContent='🔎 카드명·카드번호 자동 인식 중…';try{const [hash,text,data]=await Promise.all([imageHash(file),browserText(file),imageData(file)]);window.tcgIdentityImageHash=hash;let candidates=learnedCandidates(hash,gameName(game)),server=null;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),40000);try{const response=await fetch('/api/recognize-card',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({game:gameName(game),image_hash:hash,image_data:data,ocr_text:text}),signal:controller.signal,cache:'no-store'});server=await response.json().catch(()=>null);if(response.ok){if(server?.image_hash)window.tcgIdentityImageHash=server.image_hash;candidates=mergeCandidates([...candidates,...(server?.candidates||[])])}}catch(_){/* Static PWA or optional OCR unavailable: confirmed local visual memory remains usable. */}finally{clearTimeout(timer)}displayCandidates(candidates);const best=candidates[0];if(best){status.textContent=`✅ 후보 ${Math.round(best.confidence*100)}% · 자동 추정값은 아래에서 확인해야 학습됩니다.`}else if(['tesseract_not_installed','dependency_not_installed'].includes(server?.ocr_error)){status.textContent='OCR 구성요소가 없어 자동 문자 인식을 못했습니다. 카드명·번호를 한 번 확인 저장하면 이후 동일 카드 재인식에 학습됩니다.'}else{status.textContent='일치 후보를 찾지 못했습니다. 카드명·번호를 확인 입력한 뒤 학습해 주세요.'}return {hash:window.tcgIdentityImageHash,candidates}}catch(_){status.textContent='카드 문자 인식 중 오류가 발생했습니다. 카드 전체가 선명한 앞면 사진인지 확인해 주세요.';return null}}
function saveLocal(row){const rows=localRows(),same=rows.filter(item=>item.image_hash===row.image_hash),conflict=same.some(item=>[item.card_name,item.card_number,item.market_key,item.game].join('|')!==[row.card_name,row.card_number,row.market_key,row.game].join('|'));if(conflict)return {ok:false,conflict:true};const duplicate=rows.some(item=>[item.image_hash,item.card_name,item.card_number,item.market_key,item.game].join('|')===[row.image_hash,row.card_name,row.card_number,row.market_key,row.game].join('|'));if(!duplicate)rows.push(row);localStorage.setItem(MEMORY_KEY,JSON.stringify(rows.slice(-MAX_LOCAL)));const count=rows.filter(item=>[item.card_name,item.card_number,item.market_key,item.game].join('|')===[row.card_name,row.card_number,row.market_key,row.game].join('|')).length;return {ok:true,count}}
async function confirmIdentity(){const hash=window.tcgIdentityImageHash||'',name=safeText(byId('identityCardName').value),number=safeText(byId('identityCardNumber').value).toUpperCase().replace(/\s+/g,''),game=gameName(window.tcgIdentityGame||'pokemon');if(!/^[0-9a-f]{16}$/.test(hash)||!name){byId('identityStatus').textContent='앞면 사진과 확인된 카드명이 필요합니다.';return}const row={confirmed:true,image_hash:hash,game,card_name:name,card_number:number,market_key:safeText(byId('identityMarketKey').value),region:byId('identityRegion').value};const local=saveLocal(row);if(!local.ok){byId('identityStatus').textContent='⚠️ 같은 사진에 서로 다른 카드명이 입력되어 학습을 중단했습니다.';return}let serverSaved=false;try{const response=await fetch('/api/confirm-card-identity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(row),cache:'no-store'});if(response.ok)serverSaved=(await response.json()).ok===true}catch(_){}byId('quickCardQuery').value=[name,number].filter(Boolean).join(' ');byId('identityStatus').textContent=`✅ 인식 결과 확인 완료 · 이 카드 ${local.count}회 확인 학습${local.count>=3?' · 유사 사진 재인식 활성화':''}${serverSaved?' · 서버 동기화':''}`;byId('quickPriceSearch')?.click()}
function init(){const select=byId('identityCandidates');if(!select)return;select.addEventListener('change',()=>applyCandidate(select._rows?.[Number(select.value)]));byId('identityConfirm')?.addEventListener('click',confirmIdentity);byId('identityRetry')?.addEventListener('click',()=>recognize(window.tcgIdentityGame||'pokemon'));window.tcgRecognizeCurrentCard=game=>{window.tcgIdentityGame=gameName(game);return recognize(window.tcgIdentityGame)};window.tcgCardIdentityLearning=Object.freeze({version:'v109-confirmation-only',rows:()=>localRows().length,recognize:window.tcgRecognizeCurrentCard})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
