(()=>{
'use strict';
const $=id=>document.getElementById(id);
const krw=n=>Number(n)>0?`₩${Math.round(Number(n)).toLocaleString('ko-KR')}`:'-';
const safe=s=>String(s||'').replace(/[<>]/g,'');
function mount(){
 if($('multiMarketPanel'))return true;
 const out=$('market12out');if(!out)return false;
 const s=document.createElement('section');s.id='multiMarketPanel';s.className='multi-market-panel';
 s.innerHTML=`<div class="mmp-head"><div class="mmp-head-copy"><b>🌐 다중마켓 시세 교차검색</b><small>eBay · Amazon · KREAM · 당근 · 번개장터 · 중고나라 · Collectory · TCGplayer · Cardmarket · Mercari · Yahoo Japan</small></div><button id="multiMarketRefresh" type="button">↻ 다시 수집</button></div><div id="multiMarketSummary" class="mmp-summary mmp-wait"><b>카드 인식 후 자동 검색</b><span>카드명이나 카드번호가 들어오면 여러 마켓을 동시에 확인합니다.</span></div><div id="multiMarketRows" class="mmp-rows"></div><div id="multiMarketNote" class="mmp-note"></div>`;
 out.insertAdjacentElement('afterend',s);$('multiMarketRefresh')?.addEventListener('click',()=>load(true));return true;
}
function sourceBadge(x){return `<span class="mmp-source">${safe(x.source)}</span><span class="mmp-kind">${safe(x.price_kind||'가격')}</span>${x.verified_api?'<span class="mmp-api">API</span>':''}`}
function render(j){const sum=$('multiMarketSummary'),rows=$('multiMarketRows');if(!sum||!rows)return;const s=j.summary||{};sum.className='mmp-summary';sum.innerHTML=`<div><span>수집가격</span><b>${s.count||0}건</b></div><div><span>출처</span><b>${s.source_count||0}곳</b></div><div><span>중앙값</span><b>${krw(s.median_krw)}</b></div><div><span>가격범위</span><b>${krw(s.min_krw)} ~ ${krw(s.max_krw)}</b></div>`;rows.innerHTML=(j.items||[]).slice(0,24).map(x=>`<article class="mmp-row"><div class="mmp-top"><div class="mmp-badges">${sourceBadge(x)}</div><strong>${krw(x.price_krw)}</strong></div><div class="mmp-title">${safe(x.title)}</div><div class="mmp-meta"><span>${x.currency&&x.price_native?`${safe(x.currency)} ${Number(x.price_native).toLocaleString()}`:'원화 환산'}</span><span>${safe(x.date||'최근 검색 확인')}</span></div><a href="${x.url}" target="_blank" rel="noopener noreferrer">원문 확인 →</a></article>`).join('')||'<div class="mmp-empty"><b>가격 결과 없음</b><span>현재 공개 검색결과에서 확인 가능한 가격을 찾지 못했습니다.</span></div>';$('multiMarketNote').textContent=(j.notice||'')+(j.errors?.length?` · 일부 출처 실패 ${j.errors.length}곳`:``)}
async function load(force=false){if(!mount())return;const q=String($('query12')?.value||'').trim();if(!q){const s=$('multiMarketSummary');s.className='mmp-summary mmp-wait';s.innerHTML='<b>카드 인식 후 자동 검색</b><span>카드명이나 카드번호가 들어오면 여러 마켓을 동시에 확인합니다.</span>';$('multiMarketRows').innerHTML='';return}const region=$('market12')?.value||'ALL',game=$('v12Game')?.value||'ALL';const s=$('multiMarketSummary');s.className='mmp-summary mmp-wait';s.innerHTML='<b>여러 마켓에서 가격 수집 중…</b><span>출처별 가격을 교차확인하고 중복 결과를 정리하고 있습니다.</span>';$('multiMarketRows').innerHTML='';try{const u=`/api/multi-market-prices?q=${encodeURIComponent(q)}&region=${encodeURIComponent(region)}&game=${encodeURIComponent(game)}&force=${force?'1':'0'}&t=${Date.now()}`;const r=await fetch(u,{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'load failed');window.__multiMarketPrices=j;render(j)}catch(_){s.className='mmp-summary mmp-wait mmp-error';s.innerHTML='<b>다중마켓 수집 실패</b><span>태블릿/PC 서버 연결을 확인한 뒤 다시 수집해 주세요.</span>'}}
function boot(){let tries=0;const t=setInterval(()=>{tries++;if(mount()||tries>20)clearInterval(t)},250);mount();$('search12')?.addEventListener('click',()=>setTimeout(()=>load(false),80));window.tcgMultiMarketPrice=Object.freeze({refresh:()=>load(true)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
