(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let busy=false;
function style(){if(document.getElementById('gpdPendingOfficialV161Style'))return;const s=document.createElement('style');s.id='gpdPendingOfficialV161Style';s.textContent=`
#gpdPendingOfficialV161{margin-top:12px;border:1px solid #dbeafe;border-radius:14px;background:#fff;overflow:hidden}
.gpd-pending-toggle{width:100%;border:0;background:#eff6ff;color:#1e3a8a;padding:13px 15px;text-align:left;font-weight:900;font-size:13px;cursor:pointer}
.gpd-pending-body{padding:10px 12px}.gpd-pending-note{font-size:10px;line-height:1.55;color:#475569;margin:0 0 8px}
.gpd-pending-row{border-top:1px solid #e2e8f0;padding:10px 0}.gpd-pending-row:first-of-type{border-top:0}
.gpd-pending-title{font-size:12px;font-weight:900;color:#0f172a}.gpd-pending-meta{font-size:10px;color:#64748b;margin-top:3px;line-height:1.5}
.gpd-pending-actions{display:grid;grid-template-columns:auto 1fr auto;gap:7px;margin-top:8px;align-items:center}
.gpd-pending-open,.gpd-pending-file-label,.gpd-pending-submit{border:0;border-radius:9px;padding:9px 10px;font-size:10px;font-weight:900;text-decoration:none;display:flex;align-items:center;justify-content:center;white-space:nowrap}
.gpd-pending-open{background:#2563eb;color:#fff}.gpd-pending-file-label{background:#e2e8f0;color:#334155;cursor:pointer}.gpd-pending-submit{background:#0f766e;color:#fff;cursor:pointer}.gpd-pending-submit:disabled{opacity:.45;cursor:not-allowed}.gpd-pending-file{display:none}.gpd-pending-state{font-size:10px;margin-top:6px;color:#0f766e;font-weight:800}
@media(max-width:620px){.gpd-pending-actions{grid-template-columns:1fr 1fr}.gpd-pending-submit{grid-column:1/-1}.gpd-pending-open,.gpd-pending-file-label,.gpd-pending-submit{width:100%}}
`;document.head.appendChild(s)}
async function fileDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(new Error('파일을 읽지 못했습니다.'));r.readAsDataURL(file)})}
async function normalize(file){if(!file||!['image/jpeg','image/png'].includes(file.type))throw new Error('공식 조회 결과 화면을 JPG 또는 PNG로 선택하세요.');if(file.size>12_000_000)throw new Error('공식 조회 화면이 12MB를 초과합니다.');if(!globalThis.createImageBitmap)return fileDataUrl(file);const b=await createImageBitmap(file,{imageOrientation:'from-image'});try{const scale=Math.min(1,2200/Math.max(b.width,b.height));const c=document.createElement('canvas');c.width=Math.max(320,Math.round(b.width*scale));c.height=Math.max(320,Math.round(b.height*scale));const x=c.getContext('2d');if(!x)throw new Error('사진 변환 실패');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(b,0,0,c.width,c.height);for(const q of [.9,.82,.74]){const v=c.toDataURL('image/jpeg',q);if(v.length<8_000_000)return v}throw new Error('공식 조회 화면을 8MB 이하로 줄이지 못했습니다.')}finally{b.close?.()}}
function anchor(){return document.getElementById('gpdExistingRevalidationStatus')||[...document.querySelectorAll('button')].find(b=>String(b.textContent||'').includes('기존 등록사진')&&String(b.textContent||'').includes('재검증'))}
async function load(){try{const r=await fetch('/api/pending-official-candidates?_='+Date.now(),{cache:'no-store'});if(!r.ok)return null;return await r.json()}catch(_){return null}}
function gameLabel(v){return ({pokemon:'포켓몬',onepiece:'원피스',naruto:'나루토'})[String(v||'').toLowerCase()]||String(v||'미분류')}
async function render(){if(busy)return;busy=true;try{style();const a=anchor();if(!a)return;let box=document.getElementById('gpdPendingOfficialV161');if(!box){box=document.createElement('div');box.id='gpdPendingOfficialV161';a.insertAdjacentElement('afterend',box)}const p=await load();if(!p||!p.ok||!Number(p.pending_count||0)){box.hidden=true;return}box.hidden=false;const rows=Array.isArray(p.candidates)?p.candidates:[];const expanded=box.dataset.expanded==='1';box.innerHTML=`<button type="button" class="gpd-pending-toggle">${expanded?'▼':'▶'} 공식검증 미완료 ${Number(p.pending_count||0)}건 직접확인/등록</button><div class="gpd-pending-body" ${expanded?'':'hidden'}><p class="gpd-pending-note">자동 공식검증이 끝나지 않은 후보만 따로 표시합니다. 공식 등급사 사이트를 직접 열어 인증번호·등급을 확인한 뒤 결과 화면을 등록하세요. 화면 OCR에서 등급사+인증번호+등급이 모두 정확히 일치할 때만 공식검증 자료로 승격됩니다.</p>${rows.map(row=>`<div class="gpd-pending-row" data-candidate="${esc(row.candidate_id)}"><div class="gpd-pending-title">${esc(row.company)} ${esc(row.grade)} · ${esc(gameLabel(row.game))}</div><div class="gpd-pending-meta">인증 ${esc(row.certification_id)} · ${esc(row.source||'공개후보')}</div><div class="gpd-pending-actions"><a class="gpd-pending-open" href="${esc(row.official_reference_url)}" target="_blank" rel="noopener noreferrer">① 공식조회 열기</a><label class="gpd-pending-file-label">② 확인화면 선택<input type="file" class="gpd-pending-file" accept="image/jpeg,image/png"></label><button type="button" class="gpd-pending-submit" disabled>③ 검증완료 등록</button></div><div class="gpd-pending-state"></div></div>`).join('')}</div>`;box.querySelector('.gpd-pending-toggle')?.addEventListener('click',()=>{box.dataset.expanded=expanded?'0':'1';render()});box.querySelectorAll('.gpd-pending-row').forEach(row=>{const input=row.querySelector('.gpd-pending-file'),button=row.querySelector('.gpd-pending-submit'),state=row.querySelector('.gpd-pending-state');input?.addEventListener('change',()=>{button.disabled=!input.files?.[0];state.textContent=input.files?.[0]?`선택: ${input.files[0].name}`:''});button?.addEventListener('click',async()=>{const file=input.files?.[0];if(!file)return;button.disabled=true;state.textContent='공식 조회 화면 OCR 일치검사 중…';try{const proof_image=await normalize(file);const r=await fetch('/api/pending-official-candidate-proof',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({candidate_id:row.dataset.candidate,proof_image})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`등록 실패 (${r.status})`);if(!data.accepted){state.textContent='미등록: '+String(data.error||'정보 불일치');button.disabled=false;return}state.textContent='✓ 공식검증 완료 · 학습자료 승격';setTimeout(()=>location.reload(),900)}catch(e){state.textContent='오류: '+String(e?.message||e);button.disabled=false}})})}finally{busy=false}}
function install(){render();setInterval(render,12000);const obs=new MutationObserver(()=>{if(!busy)setTimeout(render,250)});obs.observe(document.documentElement,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
