from pathlib import Path

path = Path('ui_app_shell_v272.css')
text = path.read_text(encoding='utf-8')

replacements = {
    'box-shadow:0 4px 16px rgba(15,23,42,.045(!important': 'box-shadow:0 4px 16px rgba(15,23,42,.045)!important',
    "content:'선택남'!important": "content:'선택됨'!important",
    "content:'원하는 기능을 선택하면 해당 화면으로 바로 이동합니다' important;": "content:'원하는 기능을 선택하면 해당 화면으로 바로 이동합니다'!important;",
    '.feature-category-grid{grid-template-columns:1fr)mportant}': '.feature-category-grid{grid-template-columns:1fr!important}',
}
for old, new in replacements.items():
    text = text.replace(old, new)

block = r'''
/* v314 premium-clarity UI refinement.
   Presentation-only additive overrides: improves hierarchy, scanability, spacing,
   category recognition, and tablet usability without changing application logic. */
:root{
  --v314-canvas:#f6f8fb;
  --v314-surface:#ffffff;
  --v314-soft:#f8fafc;
  --v314-line:#e2e8f0;
  --v314-line-strong:#cbd5e1;
  --v314-ink:#0f172a;
  --v314-muted:#64748b;
  --v314-blue:#2563eb;
  --v314-blue-soft:#eff6ff;
  --v314-green:#059669;
  --v314-green-soft:#ecfdf5;
  --v314-amber:#d97706;
  --v314-amber-soft:#fffbeb;
  --v314-violet:#7c3aed;
  --v314-violet-soft:#f5f3ff;
  --v314-radius:16px;
  --v314-shadow:0 5px 18px rgba(15,23,42,.055);
}
@media(prefers-color-scheme:light){body{background:linear-gradient(180deg,#f8fafc 0%,var(--v314-canvas) 100%)!important}}
.app{padding-top:14px!important}
.app-title-primary{padding:18px 19px!important;border-radius:18px!important;background:linear-gradient(135deg,#111827 0%,#172554 68%,#1e40af 100%)!important;box-shadow:0 10px 28px rgba(15,23,42,.15)!important}
.app-title-primary h1{font-size:clamp(25px,4vw,30px)!important;line-height:1.12!important;letter-spacing:-.04em!important;margin:2px 0 7px!important}.app-title-kicker{font-size:10px!important;letter-spacing:.08em!important;color:#bfdbfe!important}.app-title-summary{max-width:72ch!important;font-size:12.5px!important;line-height:1.58!important;color:#dbeafe!important}.app-title-help{margin-top:9px!important;padding:7px 10px!important;border-radius:9px!important;background:rgba(255,255,255,.075)!important;border-color:rgba(255,255,255,.15)!important;font-size:11.5px!important}
.card,.home-launcher,.feature-category-nav,.tablet-manager-hub{border:1px solid var(--v314-line)!important;border-radius:var(--v314-radius)!important;background:var(--v314-surface)!important;box-shadow:var(--v314-shadow)!important}.card{padding:16px!important;margin:10px 0!important}.card>h2:first-child,.card>h3:first-child,.card>h4:first-child{color:var(--v314-ink)!important;font-weight:850!important;letter-spacing:-.025em!important}.card>h2:first-child{font-size:19px!important}.card>h3:first-child{font-size:17px!important}.card>h4:first-child{font-size:15px!important}.card>.muted:first-of-type{color:var(--v314-muted)!important;line-height:1.55!important}
.home-launcher{padding:14px!important}.home-launcher h2{font-size:18px!important;letter-spacing:-.025em!important}.home-launcher-grid{gap:8px!important;margin-top:10px!important}.home-launch-btn{min-height:88px!important;padding:11px 12px!important;display:grid!important;grid-template-columns:42px minmax(0,1fr)!important;grid-template-rows:auto auto!important;column-gap:10px!important;row-gap:2px!important;align-items:center!important;justify-items:start!important;text-align:left!important;border:1px solid var(--v314-line)!important;border-radius:13px!important;background:#fff!important;color:var(--v314-ink)!important;box-shadow:none!important}.home-launch-btn:first-child{border-color:#bfdbfe!important;background:#f8fbff!important}.home-launch-btn:last-child{border-color:#bbf7d0!important;background:#f8fffb!important;color:var(--v314-ink)!important}.home-launch-icon{grid-row:1/3!important;display:grid!important;place-items:center!important;width:42px!important;height:42px!important;border-radius:12px!important;background:var(--v314-blue-soft)!important;font-size:25px!important}.home-launch-btn:last-child .home-launch-icon{background:var(--v314-green-soft)!important}.home-launch-btn b{font-size:14px!important;line-height:1.25!important}.home-launch-btn small{font-size:10px!important;line-height:1.4!important;color:var(--v314-muted)!important}
.feature-category-nav{padding:15px!important}.feature-category-head{margin-bottom:9px!important}.feature-category-head h2{font-size:20px!important;line-height:1.2!important}.feature-category-head p{font-size:12px!important;line-height:1.5!important}.feature-category-count{min-height:27px!important;padding:5px 9px!important;background:#f1f5f9!important;border-color:#e2e8f0!important;color:#475569!important}.feature-category-steps{gap:6px!important;margin:8px 0!important}.feature-category-steps span{min-height:36px!important;border-radius:10px!important;background:#f8fafc!important;border-color:#e2e8f0!important;color:#475569!important;font-size:11px!important}.feature-category-steps b{width:21px!important;height:21px!important;background:#334155!important;font-size:10px!important;box-shadow:none!important}.feature-category-selected{margin:7px 0 10px!important;padding:8px 10px!important;border-radius:10px!important;background:#f8fafc!important;border-color:#e2e8f0!important;font-size:11px!important;line-height:1.45!important;color:#64748b!important}.feature-category-selected.active{background:#f0fdf4!important;border-color:#bbf7d0!important;color:#166534!important;box-shadow:inset 3px 0 0 #22c55e!important}
.feature-category-grid{gap:8px!important}.feature-category{border-radius:13px!important;border-color:#e2e8f0!important;background:#fff!important;box-shadow:none!important}.feature-category summary{min-height:76px!important;padding:10px 11px!important;gap:10px!important;align-items:center!important}.feature-category-icon{width:40px!important;height:40px!important;flex:0 0 40px!important;border-radius:11px!important;font-size:22px!important;background:#f1f5f9!important;box-shadow:none!important}.feature-category-title{font-size:13.5px!important;line-height:1.28!important;font-weight:850!important}.feature-category-sub{font-size:10px!important;line-height:1.4!important;color:#718096!important}.feature-category summary::after{min-height:23px!important;padding:4px 7px!important;border-radius:8px!important;background:#f1f5f9!important;color:#64748b!important;font-size:8.5px!important}
.feature-category[data-category-key="grading"] .feature-category-icon{background:var(--v314-blue-soft)!important;color:#1d4ed8!important}.feature-category[data-category-key="market"] .feature-category-icon{background:var(--v314-green-soft)!important;color:#047857!important}.feature-category[data-category-key="box"] .feature-category-icon{background:var(--v314-amber-soft)!important;color:#b45309!important}.feature-category[data-category-key="tablet"] .feature-category-icon{background:var(--v314-violet-soft)!important;color:#6d28d9!important}.feature-category[data-category-key="code"] .feature-category-icon{background:#f1f5f9!important;color:#334155!important}.feature-category[open]{border-color:#93c5fd!important;background:#fbfdff!important;box-shadow:0 0 0 2px rgba(37,99,235,.06)!important}.feature-category[open] summary{min-height:66px!important;background:#f8fbff!important}.feature-category[open] summary::after{content:'선택됨'!important;background:#2563eb!important;color:#fff!important}
.feature-shortcut-grid{gap:7px!important;padding:9px!important;background:#fff!important;border-top-color:#e7eef7!important}.feature-shortcut-grid::before{content:'원하는 기능을 누르면 해당 화면으로 바로 이동합니다'!important;font-size:10px!important;color:#64748b!important;padding:1px 2px 4px!important}.feature-shortcut{min-height:66px!important;padding:9px 32px 9px 10px!important;border:1px solid #e2e8f0!important;border-radius:10px!important;background:#fff!important;box-shadow:none!important}.feature-shortcut b{font-size:11.5px!important;line-height:1.3!important}.feature-shortcut small{font-size:9px!important;line-height:1.4!important}.feature-shortcut::after{width:22px!important;height:22px!important;right:9px!important;border-radius:7px!important;background:#eff6ff!important;color:#2563eb!important}
.feature-quick-search{margin:8px 0 10px!important;padding:9px 10px!important;border-radius:11px!important;border-color:#e2e8f0!important;background:#f8fafc!important;box-shadow:none!important}.feature-quick-search label{font-size:11.5px!important;margin-bottom:5px!important}.feature-quick-search input{min-height:42px!important;border-radius:9px!important;font-size:15px!important}.feature-quick-search-clear{min-height:42px!important;border-radius:9px!important}.feature-quick-search-status{font-size:10px!important;min-height:16px!important}
.grade-result-cockpit{padding:13px!important;border-radius:13px!important;background:#fff!important;border:1px solid #dbeafe!important;border-left:4px solid #2563eb!important;box-shadow:0 2px 8px rgba(15,23,42,.035)!important}.grade-result-cockpit[data-state="ready"]{border-color:#bbf7d0!important;border-left-color:#16a34a!important;background:#fff!important}.grade-cockpit-head{margin-bottom:9px!important}.grade-cockpit-head h4{font-size:16px!important}.grade-cockpit-cell,.grade-cockpit-block,.grade-cockpit-probability,.grade-cockpit-company,.metric,.status,.workflow-part{border-radius:10px!important;border-color:#e2e8f0!important;background:#f8fafc!important;box-shadow:none!important}.grade-cockpit-cell b{font-size:13.5px!important}.grade-cockpit-probability b{font-size:18px!important}.validation-stats{gap:7px!important}.validation-stats .metric{min-height:72px!important;padding:9px!important}.validation-stats .metric b{font-size:19px!important}
.analysis-list{gap:9px!important}.analysis-box,.release-item,.purchase-region,.purchase-source{border:1px solid #e2e8f0!important;border-radius:12px!important;background:#fff!important;box-shadow:none!important}.analysis-head{padding:9px 10px!important}.analysis-title{font-size:13.5px!important;font-weight:850!important}.analysis-sub,.release-meta{font-size:10px!important;line-height:1.45!important}.release-board{border-radius:16px!important;background:linear-gradient(135deg,#111827 0%,#172554 76%,#1e3a8a 100%)!important;box-shadow:0 8px 22px rgba(15,23,42,.12)!important}.top-info-tabs{padding:3px!important;gap:3px!important;border-radius:11px!important;background:rgba(255,255,255,.10)!important;border-color:rgba(255,255,255,.16)!important}.top-info-tab{min-height:40px!important;border-radius:8px!important}.top-info-tab.active{box-shadow:none!important}
.tablet-manager-hub{padding:15px!important}.tablet-manager-head h3{font-size:19px!important}.tablet-manager-grid{gap:8px!important}.tablet-manager-action{min-height:88px!important;padding:10px!important;border-radius:12px!important;display:grid!important;grid-template-columns:40px minmax(0,1fr)!important;grid-template-rows:auto auto!important;column-gap:9px!important;row-gap:2px!important;justify-items:start!important;text-align:left!important;background:#fff!important;box-shadow:none!important}.tablet-manager-icon{grid-row:1/3!important;width:40px!important;height:40px!important;border-radius:11px!important;font-size:22px!important}.tablet-manager-action b{font-size:12.5px!important}.tablet-manager-action small{font-size:9.5px!important;line-height:1.35!important}
input,select,textarea{min-height:43px!important;border-radius:9px!important;border-color:#cbd5e1!important;background:#fff!important}button{min-height:41px!important;border-radius:9px!important;font-weight:800!important}#v13search,#recalcCalibration,#siteUpdateAll{background:#2563eb!important;box-shadow:none!important}#v13clear,#resetCalibration{background:#fff!important;color:#334155!important;border:1px solid #cbd5e1!important}
body.has-app-bottom-dock .app{padding-bottom:calc(88px + env(safe-area-inset-bottom,0px))!important}body .app-bottom-dock{width:min(calc(100% - 24px),560px)!important;padding:4px!important;bottom:calc(7px + env(safe-area-inset-bottom,0px))!important;border:1px solid rgba(203,213,225,.92)!important;border-radius:14px!important;background:rgba(255,255,255,.96)!important;box-shadow:0 6px 18px rgba(15,23,42,.11)!important}body .app-bottom-dock a{min-height:46px!important;border-radius:9px!important;gap:2px!important}body .app-bottom-dock-icon{font-size:19px!important}body .app-bottom-dock-label{font-size:9.5px!important}body .app-bottom-dock a[aria-current="location"],body .app-bottom-dock a[aria-current="page"],body .app-bottom-dock a.active{color:#1d4ed8!important;background:#eff6ff!important}
@media(min-width:540px) and (max-width:900px){.app{max-width:850px!important;padding-left:18px!important;padding-right:18px!important}.feature-category-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.feature-shortcut-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.tablet-manager-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.home-launcher-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.feature-category summary{min-height:78px!important}}
@media(min-width:901px){.feature-category-grid{grid-template-columns:repeat(4,minmax(0,1fr))!important}.tablet-manager-grid{grid-template-columns:repeat(3,minmax(0,1fr))!important}}
@media(max-width:539px){.app{padding-left:11px!important;padding-right:11px!important}.app-title-primary{padding:16px 14px!important;border-radius:15px!important}.feature-category-nav{padding:11px!important}.feature-category-grid{grid-template-columns:1fr!important}.feature-category summary{min-height:70px!important;padding:9px 10px!important}.feature-shortcut{min-height:64px!important}.tablet-manager-grid{grid-template-columns:1fr!important}.tablet-manager-action{min-height:78px!important}}
@media(max-width:380px){.home-launcher-grid{grid-template-columns:1fr!important}}
@media(hover:hover) and (pointer:fine){.feature-category:hover,.feature-shortcut:hover,.analysis-box:hover,.purchase-source:hover,.home-launch-btn:hover{transform:none!important;border-color:#bfdbfe!important;box-shadow:0 3px 10px rgba(15,23,42,.045)!important}}
@media(prefers-reduced-motion:reduce){.feature-category,.feature-shortcut,.home-launch-btn,.tablet-manager-action,button{transition:none!important;transform:none!important}}
@media(prefers-color-scheme:dark){.card,.home-launcher,.feature-category-nav,.tablet-manager-hub,.home-launch-btn,.feature-category,.feature-shortcut,.analysis-box,.release-item,.purchase-region,.purchase-source{background:#111827!important;border-color:#2b3a4f!important;box-shadow:none!important}.home-launch-btn:first-child,.home-launch-btn:last-child{background:#111827!important;border-color:#334155!important}.home-launch-icon,.feature-category-icon{background:#172033!important}.feature-category[data-category-key="grading"] .feature-category-icon{background:#172554!important;color:#bfdbfe!important}.feature-category[data-category-key="market"] .feature-category-icon{background:#10261c!important;color:#86efac!important}.feature-category[data-category-key="box"] .feature-category-icon{background:#2a210d!important;color:#fde68a!important}.feature-category[data-category-key="tablet"] .feature-category-icon{background:#251640!important;color:#ddd6fe!important}.feature-category-title,.feature-shortcut b,.home-launch-btn b,.tablet-manager-action b{color:#f8fafc!important}.feature-category-sub,.feature-shortcut small,.home-launch-btn small,.tablet-manager-action small{color:#94a3b8!important}.feature-category-steps span,.feature-category-selected,.feature-quick-search,.grade-cockpit-cell,.grade-cockpit-block,.grade-cockpit-probability,.grade-cockpit-company,.metric,.status,.workflow-part{background:#172033!important;border-color:#334155!important;color:#cbd5e1!important}.feature-category[open]{background:#121d2f!important;border-color:#315b86!important}.feature-category[open] summary{background:#152238!important}input,select,textarea{background:#0f172a!important;color:#f8fafc!important;border-color:#475569!important}body .app-bottom-dock{background:rgba(15,23,42,.96)!important;border-color:#334155!important}body .app-bottom-dock a[aria-current="location"],body .app-bottom-dock a[aria-current="page"],body .app-bottom-dock a.active{color:#bfdbfe!important;background:#172554!important}}
'''

marker = '/* v314 premium-clarity UI refinement.'
if marker not in text:
    text = text.rstrip() + '\n\n' + block.strip() + '\n'

assert marker in text
assert text.count('{') == text.count('}')
for bad in ('rgba(15,23,42,.045(!important', "content:'선택남'", "' important;", '1fr)mportant'):
    assert bad not in text, bad
path.write_text(text, encoding='utf-8')
